version: "3.7"

services:
  mariadb:
    image: mariadb
    container_name: 'books_authors_db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./setup/sql/books-authors:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - some-net

  users_db:
    image: mariadb
    container_name: 'users_db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./setup/sql/users:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      some-net:
        aliases:
          - users_db

  mongo:
    image: mongo
    container_name: 'orders_db'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=orders
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./setup/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017-27019:27017-27019'
    networks:
      some-net:
        aliases:
          - orders_db

  book_module:
    container_name: 'book_module'
    restart: always
    build:
      context: BookModule
    volumes:
      - ./BookModule:/app
    environment:
      # currently hardcoded
      - DB_USER=web_user
      - DB_USER_PASS=parolaweb_user
    ports:
      - 8000:8000
    networks:
      some-net:
        aliases:
          - book-module.dev

  orders_module:
    container_name: 'orders_module'
    restart: always
    build:
      context: OrderModule
    volumes:
      - ./OrderModule:/app
    ports:
      - 8001:8001
    networks:
      some-net:
        aliases:
          - order-module.dev

  auth_module:
    container_name: 'auth_module'
    restart: always
    build:
      context: AuthModule
    volumes:
      - ./AuthModule:/app
    ports:
      - 8080:8080
    environment:
      users_db_hostname: users_db
    networks:
      some-net:
        aliases:
          - auth-module.dev

  auth_proxy_module:
    container_name: 'auth_proxy'
    restart: always
    build:
      context: GatewayModule
    volumes:
      - ./GatewayModule:/app
    ports:
      - 8002:8002
    networks:
      - some-net

  react:
    restart: always
    container_name: 'frontend-module'
    build:
      context: bookstore-client
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - some-net

networks:
  some-net:
    driver: bridge