version: "3.7"

services:
  mariadb:
    image: mariadb
    container_name: 'books_authors_db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./setup/sql/books-authors:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - some-net

  users_db:
    image: mariadb
    container_name: 'users_db'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./setup/sql/users:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - some-net

  mongo:
    image: mongo
    container_name: 'orders_db'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=orders
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./setup/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017-27019:27017-27019'

  book_module:
    restart: always
    build:
      context: BookModule
    volumes:
      - ./BookModule:/app
    environment:
      # currently hardcoded
      - DB_USER=web_user
      - DB_USER_PASS=parolaweb_user
    ports:
      - 8000:8000
    networks:
      - some-net


networks:
  some-net:
    driver: bridge