version: "3.7"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

    volumes:
      - ./setup/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - some-net

  book_module:
    restart: always
    build:
      context: BookModule
    volumes:
      - ./BookModule:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_USER_PASS=${DB_USER_PASS}
    ports:
      - 8000:8000
    networks:
      - some-net


networks:
  some-net:
    driver: bridge