version: "3.7"

services:
  book_module:
    build:
      context: BookModule
    environment:
      - DB_USER=${DB_USER}
      - DB_USER_PASS=${DB_USER_PASS}
    ports:
      - 8000:8000

networks:
    default:
        driver: digital-bookstore